# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Simple example function
#'
#' @description The \pkg{tl} package provides a uniform interface to logging
#' from both R and C++ using the same namespaced \code{tl::debug()} (and alike
#' for differ logging verbs) interface. This package (and function)
#' demonstrates it.
#'
#' @param s A character string, defaults to \dQuote{baz}
#'
#' @return Nothing is returned as the function is invoked for its side-effect.
#'
bar <- function(s = "baz") {
    invisible(.Call(`_tlexample_bar`, s))
}

